### PR TITLE
Copyright Infringement

### PR DESCRIPTION
**Pull request by JeromSar**
@ItzZarama
Hello,

It has come to my attention that this repository contains copyrighted material in violation of its provided license.
The material in question is released under the TotalFreedom General License (TFGL) [Version 1.0](https://github.com/TotalFreedom/License/blob/03bfff8a00006d46653661129004b534d6ebedc3/LICENSE.md) or [Version 2.0](https://github.com/TotalFreedom/License/blob/7e1a8d078b1c310b8ed618ce215ab77e2a7a099e/LICENSE.md) depending on the time infringing material was introduced to this repository.

Copyrighted material included in this repository violates its license due to one or more of the following:
- Redistributions of the material do not retain its copyright license in its exact form.
- The original authors of this software have been misrepresented or not reprepresented at all in one or more of the following locations:
  - _plugin.yml_ under `authors`
  - _README.md_
  - _TFM_Util.java_ under `DEVELOPERS`
- Redistributions of the material in question are available in non-source, object, packaged or compiled form.

In order to comply with the infringed material's license and its copyright restrictions, please either:
  a) Remove the copyrighted material from this repository; or
  b) Edit or adjust the required source files as necessary to comply with TFGL.

I hope to have properly and sufficiently informed you of the violations in this repository. If you have any further questions, don't hesitate to contact me.

Thanks in advance,
Jerom

### CODE REVIEW

**Comment by Alex33856** [comment]
I don't think that ItzZarama is active on github anymore.

**Comment by ItzZarama** [comment]
I quit MC, I still come SOME days

**Comment by Alex33856** [comment]
Well, you still have to merge it.

**Comment by JeromSar** [comment]
@AlexFreedomMod This is not a PR meant for merging. This repository does not support issues, so I had to contact the author by making a dummy PR.

**Comment by Alex33856** [comment]
Sorry, I was actually using email to send this and I thought it was a actual PR.

**Pull request closed without merging**
